# Generated by Django 3.2.7 on 2021-11-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['category']},
        ),
    ]
