# Generated by Django 3.2.7 on 2021-11-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Convert'),
        ),
    ]
