# Generated by Django 3.2.7 on 2021-11-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='type',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Convert'),
        ),
    ]
