# Generated by Django 3.2.7 on 2021-11-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photos_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='description',
        ),
    ]
