# Generated by Django 3.2.7 on 2021-12-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_remove_photos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Convert'),
        ),
    ]
